{
 "title": "Transcendence-Monitor",
 "refresh": "10s",
 "panels": [
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "HTTP requests duration in seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "CPU usage rate by processes in seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Time duration of each scrape in seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(scrape_duration_seconds[5m])"
    }
   ]
  }
 ]
}