groups: 
  - name: 'metrics_alerts'
    rules:
      # instance unreachable for > 5 minutes
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: page
        annotations:
          summary: 'Instance {{ $labels.instance }} down'
      
      - alert: HighRequestRate
        expr: rate(prometheus_http_requests_total[1m]) > 120
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'HTTP request rate has exceeded 120 request per minutes over the last 1 minute'
      
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[1m]) > 0.9
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Utilisation CPU élevée sur {{ $labels.instance }}"
