global:
  scrape_interval: 15s

scrape_configs:
  # scrape prometheus
  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics
    scheme: https
    static_configs:
      - targets: ['front-end:8080']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8181']
  # scrape host computer performance in docker env
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

rule_files:
  - 'alert.rules.yml'